field: 2b499a6a-3859-4d07-9410-fddd10daf919 # Blockeditor
fieldLayouts:
  6ba4b49c-6911-44e9-84b4-b8bc28646d9c:
    tabs:
      -
        elements:
          -
            fieldUid: 5d31c4e9-e99a-468f-87e6-07ac358b5c9b # formulier
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
fields:
  5d31c4e9-e99a-468f-87e6-07ac358b5c9b: # formulier
    columnSuffix: null
    contentColumnType: string
    fieldGroup: null
    handle: formulier
    instructions: ''
    name: formulier
    searchable: false
    settings:
      allowSelfRelations: false
      limit: '1'
      localizeRelations: false
      selectionLabel: ''
      showSiteMenu: false
      source: null
      sources: '*'
      targetSiteId: null
      validateRelatedElements: false
      viewMode: null
    translationKeyFormat: null
    translationMethod: site
    type: verbb\formie\fields\Forms
handle: form
name: form
sortOrder: 3
