baseUrl: $PRIMARY_SITE_URL
enabled: true
handle: default
hasUrls: true
language: en-US
name: www.mycraftproject.dev
primary: true
siteGroup: b8d09f30-1538-4217-b171-cea031f3bd17 # www.mycraftproject.dev
sortOrder: 1
