columnSuffix: vqcclnvl
contentColumnType: string
fieldGroup: 8259cd47-63d7-416a-b932-312bd5702bef # Common
handle: email
instructions: ''
name: email
searchable: false
settings:
  placeholder: ''
translationKeyFormat: null
translationMethod: none
type: craft\fields\Email
