columnSuffix: null
contentColumnType: string
fieldGroup: 8259cd47-63d7-416a-b932-312bd5702bef # Common
handle: nieuwscategorie
instructions: ''
name: Nieuwscategorie
searchable: true
settings:
  allowLimit: false
  allowMultipleSources: false
  allowSelfRelations: false
  branchLimit: '1'
  limit: null
  localizeRelations: false
  selectionLabel: ''
  showSiteMenu: true
  source: 'group:e5a5758d-b384-44fe-a4e6-e14e969e87ee' # nieuws categorie
  sources: '*'
  targetSiteId: null
  validateRelatedElements: false
  viewMode: null
translationKeyFormat: null
translationMethod: site
type: craft\fields\Categories
