fieldLayouts:
  b907c351-7540-4744-90db-50c5ddfc5062:
    tabs:
      -
        elements:
          -
            fieldUid: 59bdc6f7-0540-4ece-b1de-d77927becc26 # naam
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 838438a9-d35e-4c97-ad34-3a148145d363 # datum
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: copyright
        sortOrder: 1
handle: copyright
name: copyright
sortOrder: 2
